config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :powers
  resources :orders, only: [:new, :create, :index, :show, :destroy]
  # Defines the root path route ("/")
  # root "posts#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :power
end

app/models/power.rb
class Power < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :description, presence: true
  validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_many :powers, dependent: :destroy
  has_many :orders, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo, :first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo, :first_name, :last_name])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :destroy]
  def index
    @orders = current_user.orders
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    if @order.save
      redirect_to orders_path, notice: "Pedido criado com sucesso!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @power = @order.power
    if @order.user == current_user
      render :show
    else
      redirect_to root_path, alert: "Nao autorizado"
    end
  end

  def destroy
    @order.destroy
    redirect_to orders_path, notice: "Pedido excluido com sucesso!"
  end

private

  def order_params
    params.require(:order).permit(:power_id)
    # @power = Power.find(params[:power_id])
  end

  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/powers_controller.rb
class PowersController < ApplicationController
  before_action :set_power, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]
  def new
    @power = Power.new
  end

  def create
    @power = current_user.powers.build(power_params)
    if @power.save
      redirect_to power_path(@power), notice: "Poder criado com sucesso!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def index
    @powers = Power.all
    if params[:query].present?
      @powers = @powers.where("name ILIKE ?", "%#{params[:query]}%")
    end
  end

  def update
    if @power.update(power_params)
      redirect_to power_path(@power), notice: "Poder atualizado com sucesso!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @power.destroy
    redirect_to powers_path, notice: "Poder excluído com sucesso!"
    rescue ActiveRecord::RecordNotFound
    redirect_to powers_path, alert: "Poder não encontrado."
  end

  private

  def set_power
    @power = Power.find(params[:id])
  end

  def power_params
    params.require(:power).permit(:name, :description, :price, :category, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Awfulpowers</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <%= render "shared/navbar" %>
   <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="container-orders-index">
  <h1>Suas compras</h1>
  <div class="order-list">
    <ul class="list-group">
      <% total_price = 0 %>
      <% @orders.each do |order| %>
        <% total_price += order.power.price %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <span><%= order.power.name %></span>
            <strong><%= order.power.price %></strong>
            <%= button_to "Deletar", order_path(order), method: :delete, class: "custom-button" %>
          </li>
      <% end %>
    </ul>

        <h3 class="text-price-orders-index">Preço Total: $<%= total_price %></h3>

  </div>
</div>

app/views/orders/show.html.erb
<div class="container mt-1">
  <div class="card power-card shadow-sm p-4 d-flex flex-column justify-content-between" style="width: 600px; height: 700px;">
    <h2>Detalhes do Pedido</h2>

    <p><strong>ID do Pedido:</strong> <%= @order.id %></p>

    <p><strong>Poder:</strong> <%= @order.power.name %></p>

    <p><strong>Preço:</strong> <%= @order.power.price %></p>

    <div class="col-md-6 text-center">
      <% if @power.photo.present? %>
        <%= cl_image_tag @power.photo.key, height: 500, width: 350, crop: :fill, class: "img-fluid rounded" %>
      <% else %>
        <%= image_tag "no-image.jpg", alt: "Sem imagem", width: 350, height: 500 %>
      <% end %>
    </div>

    <p><strong>Email do Usuário:</strong> <%= @order.user.email %></p>

    <%= link_to "Voltar", orders_path, class: "custom-button" %>

  </div>
</div>

app/views/pages/home.html.erb
<div class="container-powers">
  <div class="container-home">

    <div class="header-text-home">
      <h1 data-controller="letter-highlight">Superpoderes à venda!</h1>
      <p data-controller="letter-highlight"> Porque esperar uma mutação radioativa pode</p>
      <p data-controller="letter-highlight"> levar tempo demais.</p>
    </div>

    <div class="cards-home">
      <div class="home-container">
        <div class="column">
          <%= image_tag "caroussel/img1.png", class: "img" %>
          <%= image_tag "caroussel/img2.png", class: "img" %>
          <%= image_tag "caroussel/img3.png", class: "img" %>
          <%= image_tag "caroussel/img4.png", class: "img" %>
          <%= image_tag "caroussel/img5.png", class: "img" %>
          <%= image_tag "caroussel/img1.png", class: "img" %>
          <%= image_tag "caroussel/img2.png", class: "img" %>
          <%= image_tag "caroussel/img3.png", class: "img" %>
          <%= image_tag "caroussel/img4.png", class: "img" %>
          <%= image_tag "caroussel/img5.png", class: "img" %>
          <%= image_tag "caroussel/img1.png", class: "img" %>
          <%= image_tag "caroussel/img2.png", class: "img" %>
          <%= image_tag "caroussel/img3.png", class: "img" %>
          <%= image_tag "caroussel/img4.png", class: "img" %>
          <%= image_tag "caroussel/img5.png", class: "img" %>
        </div>

        <div class="column">
          <%= image_tag "caroussel/img6.png", class: "img" %>
          <%= image_tag "caroussel/img7.png", class: "img" %>
          <%= image_tag "caroussel/img8.png", class: "img" %>
          <%= image_tag "caroussel/img9.png", class: "img" %>
          <%= image_tag "caroussel/img10.png", class: "img" %>
          <%= image_tag "caroussel/img6.png", class: "img" %>
          <%= image_tag "caroussel/img7.png", class: "img" %>
          <%= image_tag "caroussel/img8.png", class: "img" %>
          <%= image_tag "caroussel/img9.png", class: "img" %>
          <%= image_tag "caroussel/img10.png", class: "img" %>
          <%= image_tag "caroussel/img6.png", class: "img" %>
          <%= image_tag "caroussel/img7.png", class: "img" %>
          <%= image_tag "caroussel/img8.png", class: "img" %>
          <%= image_tag "caroussel/img9.png", class: "img" %>
          <%= image_tag "caroussel/img10.png", class: "img" %>
        </div>

        <div class="column">
          <%= image_tag "caroussel/img11.png", class: "img" %>
          <%= image_tag "caroussel/img12.png", class: "img" %>
          <%= image_tag "caroussel/img13.png", class: "img" %>
          <%= image_tag "caroussel/img21.png", class: "img" %>
          <%= image_tag "caroussel/img22.png", class: "img" %>
          <%= image_tag "caroussel/img11.png", class: "img" %>
          <%= image_tag "caroussel/img12.png", class: "img" %>
          <%= image_tag "caroussel/img13.png", class: "img" %>
          <%= image_tag "caroussel/img21.png", class: "img" %>
          <%= image_tag "caroussel/img22.png", class: "img" %>
          <%= image_tag "caroussel/img11.png", class: "img" %>
          <%= image_tag "caroussel/img12.png", class: "img" %>
          <%= image_tag "caroussel/img13.png", class: "img" %>
          <%= image_tag "caroussel/img21.png", class: "img" %>
          <%= image_tag "caroussel/img22.png", class: "img" %>
        </div>

        <div class="column">
          <%= image_tag "caroussel/img16.png", class: "img" %>
          <%= image_tag "caroussel/img17.png", class: "img" %>
          <%= image_tag "caroussel/img18.png", class: "img" %>
          <%= image_tag "caroussel/img19.png", class: "img" %>
          <%= image_tag "caroussel/img20.png", class: "img" %>
          <%= image_tag "caroussel/img16.png", class: "img" %>
          <%= image_tag "caroussel/img17.png", class: "img" %>
          <%= image_tag "caroussel/img18.png", class: "img" %>
          <%= image_tag "caroussel/img19.png", class: "img" %>
          <%= image_tag "caroussel/img20.png", class: "img" %>
          <%= image_tag "caroussel/img16.png", class: "img" %>
          <%= image_tag "caroussel/img17.png", class: "img" %>
          <%= image_tag "caroussel/img18.png", class: "img" %>
          <%= image_tag "caroussel/img19.png", class: "img" %>
          <%= image_tag "caroussel/img20.png", class: "img" %>
        </div>
      </div>
     </div>
  </div>

app/views/powers/edit.html.erb
<div class="form-container-edit-powers">
  <h2>Edite seu Poder</h2>
    <%= simple_form_for(@power) do |f| %>

      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs-edit-powers">
        <label class="login-label-edit-powers">Nome:</label>
        <%= f.input :name, label: false, required: true, input_html: { autocomplete: "name" } %>
        <label class="login-label-edi-powers">Preço:</label>
        <%= f.input :price, label: false, required: true, input_html: { autocomplete: "price" } %>
        <label class="login-label-edit-powers">Descrição:</label>
        <%= f.input :description, label: false, required: true, input_html: { autocomplete: "description" } %>
        <label class="login-label-edit-powers">Categoria:</label>
        <%= f.input :category, label: false, required: true, input_html: { autocomplete: "category" } %>
        <label class="login-label-edit-powers">Seu Card:</label>
        <%= f.input :photo, as: :file, label: false, input_html: { autocomplete: "photo" } %>

      </div>
      <div class="power-button-edit-group">
      <div class="form-btn-edit-powers">
        <%= f.button :submit, class: "custom-button-edit-powers"%>
        <%= button_to 'Voltar', powers_path , class: "custom-button-edit-powers" %>
      </div>
    <% end %>
</div>

app/views/powers/index.html.erb
<h1>Lista de poderes disponíveis</h1>

<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: powers_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-search",
            placeholder: "Pesquisar um poder"
        %>
      <%= submit_tag "Pesquisar", name: "", class: "custom-button-search" %>
    <% end %>
  </div>
</div>

<ul>
  <div class="card-container-index">
    <% @powers.each do |power| %>
      <%= link_to power_path(power), class: "card-link" do %>
        <div class="card">
          <div class="card-image">
            <% if power.photo.present? %>
              <%= cl_image_tag power.photo.key, height: 450, width: 350 %>
            <% else %>
              <%= image_tag "no-image.jpg", alt: "Sem imagem" %>
            <% end %>
          </div>
          <li><strong><%= power.name %></strong></li>
          <li class="text-price-orders-index">$<%= power.price %></li>
        </div>
      <% end %>
    <% end %>
  </div>
</ul>

app/views/powers/new.html.erb
<div class="fix-container">
  <div class="form-container-new-powers">
    <h2>Novo Poder</h2>

      <%= simple_form_for(@power) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs-new-powers">
          <label class="login-label-new-powers">Nome:</label>
          <%= f.input :name, label: false, required: true, input_html: { autocomplete: "name" } %>
          <label class="login-label-new-powers">Preço:</label>
          <%= f.input :price, label: false, required: true, input_html: { autocomplete: "price" } %>
          <label class="login-label-new-powers">Descrição:</label>
          <%= f.input :description, label: false, required: true, input_html: { autocomplete: "description" } %>
          <label class="login-label-new-powers">Categoria:</label>
          <%= f.input :category, label: false, required: true, input_html: { autocomplete: "category" } %>
          <label class="login-label-new-powers">Seu Card:</label>
          <%= f.input :photo, as: :file, label: false, input_html: { autocomplete: "photo" } %>

        </div>

        <div>
          <%= f.button :submit, "Vender", class: "new-powers-button" %>
        </div>
      <% end %>

      <div>
        <%= link_to 'Voltar', powers_path %>
      </div>
  </div>
</div>

app/views/powers/show.html.erb
<div class="power-container">
  <div class="power-row">
    <div class="power-image">
      <% if @power.photo.present? %>
        <%= cl_image_tag @power.photo.key, height: 500, width: 350, crop: :fill, class: "power-img" %>
      <% else %>
        <%= image_tag "no-image.jpg", alt: "Sem imagem", width: 350, height: 500, class: "power-img" %>
      <% end %>
    </div>

    <div class="power-details">
      <div class="power-card">
        <div class="power-card-body">
          <h2 class="power-title"><%= @power.name %></h2>
          <h3 class="power-subtitle">Descrição do poder</h3>
          <p class="power-text"><%= @power.description %></p>
          <p class="power-price">$<%= @power.price %></p>

          <div class="power-button-group">
            <%= button_to "Comprar", orders_path(order: { power_id: @power.id }),
                data: { turbo_method: :post }, class: "power-button" %>

            <% if @power.user == current_user %>
              <%= button_to "Editar", edit_power_path(@power), method: :get, class: "power-button" %>
              <%= button_to "Deletar", power_path(@power), method: :delete, class: "power-button" %>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg custom-navbar">
  <div data-controller="user-menu" class="container-fluid d-flex align-items-center justify-content-between">
    <a class="navbar-brand" href="/">
      <%= image_tag "logo_navbar.png", alt: "AwfulPowers" %>
    </a>

    <% if user_signed_in? %>
      <div class="nav-list">
        <%= link_to 'HOME', root_path, class: 'nav-link custom-nav-link' %>
        <%= link_to 'SOBRE', root_path, class: 'nav-link custom-nav-link' %>
        <%= link_to 'CONTATO', root_path, class: 'nav-link custom-nav-link' %>
        <div class="relative" data-action="click@document->user-menu#close">
          <button id="user-menu-button" class="user-avatar-button" data-action="click->user-menu#toggle">
            <% if current_user.photo.present? %>
              <%= image_tag current_user.photo, class: "user-avatar" %>
            <% else %>
              <%= image_tag "no-avatar.jpg", class: "user-avatar" %>
            <% end %>
          </button>
          <div id="user-menu"
          data-user-menu-target="menu"
          class="hidden absolute right-0 mt-2 w-48 bg-white shadow-lg rounded-lg z-50">
            <%= link_to "Meus pedidos", orders_path, class: "block px-4 py-2 text-gray-700 hover:bg-gray-200" %>
            <%= link_to 'Comprar', powers_path, class: 'block px-4 py-2 text-gray-700 hover:bg-gray-200' %>
            <%= link_to "Vender", new_power_path, class: "block px-4 py-2 text-gray-700 hover:bg-gray-200" %>
            <%= button_to "Sair", destroy_user_session_path, method: :delete,
            class: "block px-4 py-2 text-gray-700 hover:bg-gray-200"%>

          </div>
        </div>
      </div>
    <% else %>
      <div class="nav-list">
        <%= link_to 'HOME', root_path, class: 'nav-link custom-nav-link' %>
        <%= link_to 'SOBRE', '#', class: 'nav-link custom-nav-link' %>
        <%= link_to 'CONTATO', '#', class: 'nav-link custom-nav-link' %>
        <%= link_to "Login", new_user_session_path, class: "btn custom-button" %>
        <%= link_to "Cadastrar", new_user_registration_path, class: "btn custom-button" %>
      </div>
    <% end %>
  </div>
</nav>